title: LeMisieur Services
author: J-F Poulin
email: me@lemisieur.com
description: > # this means to ignore newlines until "show_exerpts:"
  Iâ€™ve spent the last 10 years helping one of the major retailers in Canada achieve their deployments and automation goals,
  from driving cloud adoption to migrate existing on-prem infrastructure to the cloud.
  I'm also a big fan of video capture and editing, so hit me up if you need help with that too!

show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/lemisieur
      icon: github
      color: purple
    - url: https://youtube.com/alittlefurther
      icon: youtube
      color: red
    - url: https://www.linkedin.com/in/poulinjf/
      icon: linkedin
      color: blue
    - url: mailto:me@lemisieur.com
      icon: envelope
      color: green

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: lemisieur
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
remote_theme: bitbrain/jekyll-dash
#theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-remote-theme
